@WebApiForAvalonia_HostAddress = http://localhost:5119

### Get All
GET {{WebApiForAvalonia_HostAddress}}/api/todo/
Accept: application/json

### Get specific
GET {{WebApiForAvalonia_HostAddress}}/api/todo/3
Accept: application/json

### itp
