@ApiService = http://localhost:5119
@AuthService = http://localhost:5201
@LoggerService = http://localhost:5115

### Get All
GET {{ApiService}}/api/todo/
Accept: application/json

### Get specific
GET {{ApiService}}/api/todo/3
Accept: application/json

### Get the token from AuthService
POST {{AuthService}}/auth/token
Content-Type: application/json

{
  "username": "demo",
  "password": "demo"
}

### Send a log message to LoggerService
POST {{LoggerService}}/logs
Content-Type: application/json

{
  "message": "This is a test message.",
  "type": 0
}
