@ApiService = http://localhost:5119
@AuthService = http://localhost:5201

### Get All
GET {{ApiService}}/api/todo/
Accept: application/json

### Get specific
GET {{ApiService}}/api/todo/3
Accept: application/json

### Get the token from AuthService
POST {{AuthService}}/auth/token
Content-Type: application/json

{
  "username": "demo",
  "password": "demo"
}
